2018-07-31 20:32:41.84806 [T00001] [Error]   KdDbContextFactory - DbContext Initialize Error and Retry: [KdCore.Data.Dicts.KdDbDictsContext]. 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2018-07-31 20:32:41.89710 [T00001] [Error]   KdDbContextFactory - DbContext Initialize Error: [KdCore.Data.Dicts.KdDbDictsContext]. 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
              【Exception】System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
                 在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                 在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                 在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                 在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                 在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                 在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                 在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                 在 System.Data.SqlClient.SqlConnection.Open()
                 在 System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection t, DbConnectionInterceptionContext c)
                 在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
                 在 System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
                 在 System.Data.Entity.SqlServer.SqlProviderServices.<>c__DisplayClass33.<UsingConnection>b__32()
                 在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
                 在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
                 在 System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
                 在 System.Data.Entity.SqlServer.SqlProviderServices.UsingConnection(DbConnection sqlConnection, Action`1 act)
                 在 System.Data.Entity.SqlServer.SqlProviderServices.UsingMasterConnection(DbConnection sqlConnection, Action`1 act)
                 在 System.Data.Entity.SqlServer.SqlProviderServices.CreateDatabaseFromScript(Nullable`1 commandTimeout, DbConnection sqlConnection, String createDatabaseScript)
                 在 System.Data.Entity.SqlServer.SqlProviderServices.DbCreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
                 在 System.Data.Entity.Core.Common.DbProviderServices.CreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
                 在 System.Data.Entity.Core.Objects.ObjectContext.CreateDatabase()
                 在 System.Data.Entity.Migrations.Utilities.DatabaseCreator.Create(DbConnection connection)
                 在 System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
                 在 System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
                 在 System.Data.Entity.MigrateDatabaseToLatestVersion`2.InitializeDatabase(TContext context)
                 在 KdCore.Data.EntityFramework.KdDbAutoMigrate`1.TDbMigrateToLastVersion.InitializeDatabase(TDbContext context)
                 在 System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()
                 在 System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
                 在 System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
                 在 System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
                 在 System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
                 在 System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
                 在 System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
                 在 System.Data.Entity.Internal.InternalContext.Initialize()
                 在 System.Data.Entity.Database.Initialize(Boolean force)
                 在 KdCore.Data.EntityFramework.KdDbContextFactory.DbInitialize[TDbContext]()
              ClientConnectionId:00000000-0000-0000-0000-000000000000
              Error Number:2,State:0,Class:20
